# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from myTest import square
def test_square_gives_correct_value():
  subject = square(2)
  assert subject ==4